### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by gab618** [gab618/twitter-clone#1]
- [ ] VSCode extensions
  - [ ] Colorize
  - [ ] vscode-styled-components
- [ ] Create react-app with typescript template
- [ ] Remove unecessary files
- [ ] Add ```styled-components``` and ```styled-icons``` as dependency
- [ ] Disable ```isolated-modules``` at ```tsconfig.json```
- [ ] Add ```@types/styled-components``` as dev denpendency
- [ ] Create Layout and all components
- [ ] Publish to GitHub
- [ ] Readme
